// Países disponibles
export const paisesAmericaLatina = [
  "Argentina",
  "Bolivia", 
  "Brasil",
  "Chile",
  "Colombia",
  "Costa Rica",
  "Cuba",
  "Ecuador",
  "El Salvador",
  "Estados Unidos",
  "Guatemala",
  "Honduras",
  "México",
  "Nicaragua",
  "Panamá",
  "Paraguay",
  "Perú",
  "República Dominicana",
  "Uruguay",
  "Venezuela"
];

// Estados de México
export const estadosMexico = [
  "Aguascalientes",
  "Baja California",
  "Baja California Sur",
  "Campeche",
  "Chiapas",
  "Chihuahua",
  "Ciudad de México",
  "Coahuila",
  "Colima",
  "Durango",
  "Estado de México",
  "Guanajuato",
  "Guerrero",
  "Hidalgo",
  "Jalisco",
  "Michoacán",
  "Morelos",
  "Nayarit",
  "Nuevo León",
  "Oaxaca",
  "Puebla",
  "Querétaro",
  "Quintana Roo",
  "San Luis Potosí",
  "Sinaloa",
  "Sonora",
  "Tabasco",
  "Tamaulipas",
  "Tlaxcala",
  "Veracruz",
  "Yucatán",
  "Zacatecas"
];

// Ciudades por estado (principales ciudades)
export const ciudadesPorEstado: Record<string, string[]> = {
  "Aguascalientes": ["Aguascalientes", "Calvillo", "Jesús María"],
  "Baja California": ["Tijuana", "Mexicali", "Ensenada", "Tecate", "Rosarito"],
  "Baja California Sur": ["La Paz", "Los Cabos", "Loreto", "Comondú"],
  "Campeche": ["Campeche", "Ciudad del Carmen", "Champotón"],
  "Chiapas": ["Tuxtla Gutiérrez", "Tapachula", "San Cristóbal de las Casas", "Comitán"],
  "Chihuahua": ["Chihuahua", "Ciudad Juárez", "Delicias", "Parral"],
  "Ciudad de México": ["Álvaro Obregón", "Azcapotzalco", "Benito Juárez", "Coyoacán", "Cuauhtémoc", "Gustavo A. Madero", "Iztacalco", "Iztapalapa", "Magdalena Contreras", "Miguel Hidalgo", "Milpa Alta", "Tláhuac", "Tlalpan", "Venustiano Carranza", "Xochimilco"],
  "Coahuila": ["Saltillo", "Torreón", "Monclova", "Piedras Negras"],
  "Colima": ["Colima", "Manzanillo", "Tecomán"],
  "Durango": ["Durango", "Gómez Palacio", "Lerdo"],
  "Estado de México": ["Toluca", "Ecatepec", "Naucalpan", "Tlalnepantla", "Chimalhuacán", "Nezahualcóyotl"],
  "Guanajuato": ["León", "Irapuato", "Celaya", "Salamanca", "Guanajuato"],
  "Guerrero": ["Acapulco", "Chilpancingo", "Iguala", "Taxco"],
  "Hidalgo": ["Pachuca", "Tulancingo", "Tizayuca"],
  "Jalisco": ["Guadalajara", "Zapopan", "Tlaquepaque", "Tonalá", "Puerto Vallarta"],
  "Michoacán": ["Morelia", "Uruapan", "Zamora", "Lázaro Cárdenas"],
  "Morelos": ["Cuernavaca", "Jiutepec", "Temixco"],
  "Nayarit": ["Tepic", "Bahía de Banderas", "Santiago Ixcuintla"],
  "Nuevo León": ["Monterrey", "Guadalupe", "San Nicolás de los Garza", "Apodaca", "Santa Catarina"],
  "Oaxaca": ["Oaxaca de Juárez", "Salina Cruz", "Tuxtepec"],
  "Puebla": ["Puebla", "Tehuacán", "San Martín Texmelucan"],
  "Querétaro": ["Querétaro", "San Juan del Río", "Corregidora"],
  "Quintana Roo": ["Cancún", "Chetumal", "Playa del Carmen", "Cozumel"],
  "San Luis Potosí": ["San Luis Potosí", "Soledad de Graciano Sánchez", "Ciudad Valles"],
  "Sinaloa": ["Culiacán", "Mazatlán", "Los Mochis", "Guasave"],
  "Sonora": ["Hermosillo", "Ciudad Obregón", "Nogales", "Navojoa"],
  "Tabasco": ["Villahermosa", "Cárdenas", "Comalcalco"],
  "Tamaulipas": ["Reynosa", "Matamoros", "Nuevo Laredo", "Tampico"],
  "Tlaxcala": ["Tlaxcala", "Huamantla", "Apizaco"],
  "Veracruz": ["Veracruz", "Xalapa", "Coatzacoalcos", "Córdoba", "Poza Rica"],
  "Yucatán": ["Mérida", "Kanasín", "Umán", "Progreso"],
  "Zacatecas": ["Zacatecas", "Fresnillo", "Guadalupe"]
};